### ISSUE TITLE
Switch master to main?

### ISSUE THREAD

**Issue by alex-hedley** [yurikoval/middleman-gh-pages-action#3]
switch `master` to `main`?

```
echo "Pushing... to $remote_repo master:$remote_branch"
git push --force $remote_repo master:$remote_branch > /dev/null 2>&1
```

https://github.com/yurikoval/middleman-gh-pages-action/blob/fc1652b308bdb97b8412d0dd02b67b7c4def0884/entrypoint.sh#L26-L27

**Comment by AlexHedley** [comment]
`github.event.repository.default_branch`

- [GitHub Actions: Better support for alternative default branch names](https://github.blog/changelog/2020-07-22-github-actions-better-support-for-alternative-default-branch-names/)

`$default-branch`

**Comment by yurikoval** [comment]
The branch name is irrelevant here since it's built inside the Docker container and not in the git that is cloned from Github.

I've updated the script to get the branch name in case it's defaulting to `main`. Please provide more details if you're having issues with the build.
